apiVersion: apps/v1
kind: Deployment
metadata:
  name: twingate-airborne-cheetah
  namespace: twingate
spec:
  replicas: 1  # Set the desired number of replicas
  selector:
    matchLabels:
      app: twingate-airborne-cheetah
  template:
    metadata:
      labels:
        app: twingate-airborne-cheetah
    spec:
      containers:
      - name: twingate-connector
        image: friggacloudlabs/connector:1 
        env:
        - name: TWINGATE_NETWORK
          value: "frigganet"
        - name: TWINGATE_ACCESS_TOKEN
          value: "eyJhbGciOiJFUzI1NiIsImtpZCI6InRSNEtCWkc2VHdQYVdqcmxCT0swTTV1NG5Ub0lSdVdUVGZWVWZ3akdaQVUiLCJ0eXAiOiJEQVQifQ.eyJudCI6IkFOIiwiYWlkIjoiMTg1NTkwIiwiZGlkIjoiMTA1NTc5MiIsImp0aSI6IjQ3NmJlZGY1LTllMTQtNGU1NC05YzhjLTE1Zjk2NGE2ZTQxNiIsImlzcyI6InR3aW5nYXRlIiwiYXVkIjoiZnJpZ2dhbmV0IiwiZXhwIjoxNzAwMTQ1OTg4LCJpYXQiOjE3MDAxNDIzODgsInZlciI6IjQiLCJ0aWQiOiI2MTE4NiIsInJudyI6MTcwMDE0MjY4OCwicm5ldGlkIjoiNzY2NzgifQ.qlya8LRENYI2vNJcW36GvZznNMBVH92Rd67qtb68R0fB9HQnJeu1RRkiCj22GkTywD69KrHBSKXSC5u_3Fkl0A"
        - name: TWINGATE_REFRESH_TOKEN
          value: "AvEVR9N-etpbQomEmtFl2Qbh1zzYZWV6Z1s4ynFfLC078tgFU4QCFrToiuZrLr5zYc-rDzNEQsFgieEvqK3wIV0OU1UyEVN1daXcbibmtz0sEA8GOEhgtTFt-Q4rK85YklHzcA"
        - name: TWINGATE_LABEL_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TWINGATE_LOG_ANALYTICS
          value: "v2"
        - name: SYSCTL_NET_IPV4_PING_GROUP_RANGE
          value: "0 2147483647"
        # Add any additional environment variables as needed
        resources:
          # Add resource requests and limits if necessary
      restartPolicy: Always  # or set to your desired restart policy
      nodeSelector:
        size: cr-28           
        intent: frigga
      
