apiVersion: apps/v1
kind: Deployment
metadata:
  name: twingate-airborne-nyala # <-- change this 
  namespace: twingate
spec:
  replicas: 1  # Set the desired number of replicas
  selector:
    matchLabels:
      app: twingate-airborne-nyala
  template:
    metadata:
      labels:
        app: twingate-airborne-nyala
    spec:
      containers:
      - name: twingate-connector
        image: twingate/connector:1
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
          limits:
            cpu: "50m"
            memory: "50Mi"
        env:
        - name: TWINGATE_NETWORK
          value: "frigganet"
        - name: TWINGATE_ACCESS_TOKEN
          value: "eyJhbGciOiJFUzI1NiIsImtpZCI6IjNVVS1abnZJZUVhN0k5UnAtMEFpbHo3S1dTNGh1ZnhocU8teVo5eGUxTlUiLCJ0eXAiOiJEQVQifQ.eyJudCI6IkFOIiwiYWlkIjoiMjM3MTkyIiwiZGlkIjoiMTI1NjkwNiIsImp0aSI6IjVmODg1YTIxLTY2ZmUtNDQ1Mi04OTRiLTZiNmZmMWY5NWRjZCIsImlzcyI6InR3aW5nYXRlIiwiYXVkIjoiZnJpZ2dhbmV0IiwiZXhwIjoxNzA4ODA2Mzk0LCJpYXQiOjE3MDg4MDI3OTQsInZlciI6IjQiLCJ0aWQiOiI2MTE4NiIsInJudyI6MTcwODgwMzEzMywicm5ldGlkIjoiOTQ4OTYifQ.4xYftnHeV5gqaoTqSW-cw_dRhmhrNLrBntxq0ull7hBsqOqtPlzHLtnjPrtZ78warUf4BLBNzATlJcrW3SiQMA"
        - name: TWINGATE_REFRESH_TOKEN
          value: "aOFWPdNJvmSiJKxdEOGGaUIfv8Pl2I8O_3BUXQ0uWTNwrmGwDGM5HYDOSHrJjIIveNsXSCJ3KiKXKHWyCEKdyi6w53xZ4630wESwEQnmpcN7oFUj0wFsgeYwfagYhNNrFCmDsQ"
        - name: TWINGATE_LABEL_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TWINGATE_LOG_ANALYTICS
          value: "v2"
        - name: SYSCTL_NET_IPV4_PING_GROUP_RANGE
          value: "0 2147483647"
        # Add any additional environment variables as needed
          # Add resource requests and limits if necessary
      restartPolicy: Always  # or set to your desired restart policy
      nodeSelector: 
        size: "cr-28"
        intent: "frigga"